# Generated by Django 3.0.2 on 2020-02-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, default='example', max_length=100)),
                ('profileimage', models.FileField(blank=True, upload_to='')),
                ('Password', models.CharField(blank=True, default='null', max_length=100)),
                ('Email', models.EmailField(blank=True, default='123@123.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='sample', max_length=100)),
                ('Email', models.CharField(blank=True, default='sample@sample.sample', max_length=100)),
                ('attendance', models.CharField(blank=True, default='absent', max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(blank=True, default='Father Name', max_length=100)),
                ('MotherName', models.CharField(blank=True, default='Mother Name', max_length=100)),
                ('KidName', models.CharField(blank=True, default='Kid Name', max_length=100)),
                ('Email', models.CharField(blank=True, default='Email Address', max_length=100)),
                ('Password', models.CharField(blank=True, default='Password', max_length=100)),
                ('Address', models.CharField(blank=True, default='Address', max_length=100)),
                ('ProfileImage', models.FileField(blank=True, upload_to='')),
                ('Age', models.CharField(blank=True, default='0', max_length=100)),
                ('Phone', models.CharField(blank=True, default='1234567890', max_length=100)),
                ('status', models.CharField(blank=True, default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='sample', max_length=100)),
                ('Image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffName', models.CharField(blank=True, max_length=100)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(blank=True, default='example', max_length=100)),
                ('profileimage', models.FileField(blank=True, default='default.jpg', upload_to='')),
                ('Phoneno', models.IntegerField(blank=True, default=1)),
                ('Password', models.CharField(blank=True, default='password', max_length=100)),
                ('Salary', models.IntegerField()),
                ('Email', models.EmailField(blank=True, default='123@123.com', max_length=254)),
                ('Status', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
