# Generated by Django 3.0.2 on 2020-02-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='status',
        ),
    ]
