# Generated by Django 3.0.2 on 2020-02-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zara', '0002_remove_parent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='status',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
