# Generated by Django 3.0.2 on 2020-02-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zara', '0004_parent_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='Name',
        ),
    ]
